import { MigrationInterface, QueryRunner } from "typeorm";

export class NewMigration1771822425449 implements MigrationInterface {
    name = 'NewMigration1771822425449'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."verification_log_entity_status_enum" AS ENUM('valid', 'invalid', 'already_used', 'cancelled', 'expired', 'event_not_started', 'event_ended')`);
        await queryRunner.query(`CREATE TABLE "verification_log_entity" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ticketCode" character varying NOT NULL, "ticketId" character varying, "eventId" character varying NOT NULL, "status" "public"."verification_log_entity_status_enum" NOT NULL, "verifierId" character varying, "message" character varying NOT NULL, "attemptedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4165aa9b0a7e25681b8ae8e039d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e89714329d20292076695c82b3" ON "verification_log_entity" ("eventId", "ticketId") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."event_status_enum" AS ENUM('DRAFT', 'PUBLISHED', 'CANCELLED', 'POSTPONED', 'COMPLETED')`);
        await queryRunner.query(`CREATE TYPE "public"."event_blockchainstatus_enum" AS ENUM('PENDING', 'ANCHORED', 'FAILED', 'VERIFIED')`);
        await queryRunner.query(`CREATE TABLE "event" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "eventDate" TIMESTAMP NOT NULL, "eventClosingDate" TIMESTAMP NOT NULL, "description" text NOT NULL, "capacity" integer NOT NULL, "status" "public"."event_status_enum" NOT NULL DEFAULT 'DRAFT', "isArchived" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "blockchainAnchorHash" character varying(255), "blockchainTransactionId" character varying(255), "blockchainStatus" "public"."event_blockchainstatus_enum", "blockchainAnchoredAt" TIMESTAMP, "blockchainVerifiedAt" TIMESTAMP, CONSTRAINT "PK_30c2f3bbaf6d34a55f8ae6e4614" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."ticket_types_pricetype_enum" AS ENUM('free', 'paid')`);
        await queryRunner.query(`CREATE TABLE "ticket_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, "priceType" "public"."ticket_types_pricetype_enum" NOT NULL DEFAULT 'free', "price" numeric(10,2) NOT NULL DEFAULT '0', "totalQuantity" integer NOT NULL, "soldQuantity" integer NOT NULL DEFAULT '0', "maxPerPerson" integer, "saleStartsAt" TIMESTAMP, "saleEndsAt" TIMESTAMP, "isActive" boolean NOT NULL DEFAULT true, "eventId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5510ce7e18a4edc648c9fbfc283" PRIMARY KEY ("id")); COMMENT ON COLUMN "ticket_types"."price" IS 'Price in cents or major currency unit'; COMMENT ON COLUMN "ticket_types"."totalQuantity" IS 'Total quantity available for this ticket type'; COMMENT ON COLUMN "ticket_types"."soldQuantity" IS 'Number of tickets sold/issued'; COMMENT ON COLUMN "ticket_types"."maxPerPerson" IS 'Max tickets per person. NULL = unlimited'; COMMENT ON COLUMN "ticket_types"."saleStartsAt" IS 'When ticket sales start. NULL = immediately available'; COMMENT ON COLUMN "ticket_types"."saleEndsAt" IS 'When ticket sales end. NULL = until event date'; COMMENT ON COLUMN "ticket_types"."isActive" IS 'Whether this ticket type is currently available'`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5ce97de5dda8351bef7c2205a5" ON "ticket_types" ("eventId", "name") `);
        await queryRunner.query(`CREATE TYPE "public"."tickets_status_enum" AS ENUM('issued', 'scanned', 'refunded', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "tickets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "qrCode" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" "public"."tickets_status_enum" NOT NULL DEFAULT 'issued', "orderReference" character varying, "attendeeEmail" character varying, "attendeeName" character varying, "metadata" character varying, "ticketTypeId" uuid NOT NULL, "eventId" uuid NOT NULL, "scannedAt" TIMESTAMP, "refundedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_fededfa934cf8d7214adfa6c824" UNIQUE ("qrCode"), CONSTRAINT "PK_343bc942ae261cf7a1377f48fd0" PRIMARY KEY ("id")); COMMENT ON COLUMN "tickets"."qrCode" IS 'Unique QR code identifier for scanning'; COMMENT ON COLUMN "tickets"."orderReference" IS 'Reference to order/transaction if purchased'; COMMENT ON COLUMN "tickets"."attendeeEmail" IS 'Attendee email or contact info'; COMMENT ON COLUMN "tickets"."attendeeName" IS 'Attendee name'; COMMENT ON COLUMN "tickets"."metadata" IS 'Additional metadata as JSON'; COMMENT ON COLUMN "tickets"."scannedAt" IS 'When ticket was scanned/used'; COMMENT ON COLUMN "tickets"."refundedAt" IS 'When ticket was refunded'`);
        await queryRunner.query(`CREATE INDEX "IDX_7094a7713eda319cf663dc9334" ON "tickets" ("orderReference") `);
        await queryRunner.query(`CREATE INDEX "IDX_986a0e7a5cc4bddaf417728250" ON "tickets" ("eventId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_698f411fd2aca313683603485a" ON "tickets" ("ticketTypeId", "status") `);
        await queryRunner.query(`CREATE TABLE "contact_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "email" character varying(255) NOT NULL, "subject" character varying(150) NOT NULL, "message" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b74f96eb2edd977ccfba6533293" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."blockchain_anchor_entitytype_enum" AS ENUM('EVENT', 'TICKET', 'TICKET_TRANSFER', 'EVENT_VERIFICATION')`);
        await queryRunner.query(`CREATE TYPE "public"."blockchain_anchor_status_enum" AS ENUM('PENDING', 'ANCHORED', 'FAILED', 'VERIFIED')`);
        await queryRunner.query(`CREATE TABLE "blockchain_anchor" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entityId" character varying(255) NOT NULL, "entityType" "public"."blockchain_anchor_entitytype_enum" NOT NULL, "anchorHash" character varying(255), "transactionId" character varying(255), "status" "public"."blockchain_anchor_status_enum" NOT NULL DEFAULT 'PENDING', "anchoredData" text, "metadata" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "verifiedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d649158eb87daeed477fa18b462" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_076bdf5608ee894054033d1e7f" ON "blockchain_anchor" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_73c17c036d025e548b4a08edfe" ON "blockchain_anchor" ("anchorHash") `);
        await queryRunner.query(`CREATE INDEX "IDX_349ebd8ed5a92c62ae7019d954" ON "blockchain_anchor" ("entityId", "entityType") `);
        await queryRunner.query(`CREATE TYPE "public"."user_role_enum" AS ENUM('SUBSCRIBER', 'ADMIN')`);
        await queryRunner.query(`CREATE TABLE "user" ("id" SERIAL NOT NULL, "email" character varying NOT NULL, "fullName" character varying NOT NULL, "password" character varying NOT NULL, "role" "public"."user_role_enum" NOT NULL DEFAULT 'SUBSCRIBER', "verificationCode" character varying, "verificationCodeExpiresAt" TIMESTAMP NOT NULL DEFAULT now(), "passwordResetCode" character varying, "isVerified" boolean NOT NULL DEFAULT false, "passwordResetCodeExpiresAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "UQ_fededfa934cf8d7214adfa6c824"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP COLUMN "qrCode"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7094a7713eda319cf663dc9334"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP COLUMN "orderReference"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP COLUMN "attendeeEmail"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP COLUMN "attendeeName"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP COLUMN "ticketTypeId"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP COLUMN "eventId"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP COLUMN "scannedAt"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP COLUMN "refundedAt"`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD "qrCode" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "UQ_fededfa934cf8d7214adfa6c824" UNIQUE ("qrCode")`);
        await queryRunner.query(`COMMENT ON COLUMN "tickets"."qrCode" IS 'Unique QR code identifier for scanning'`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD "orderReference" character varying`);
        await queryRunner.query(`COMMENT ON COLUMN "tickets"."orderReference" IS 'Reference to order/transaction if purchased'`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD "attendeeEmail" character varying`);
        await queryRunner.query(`COMMENT ON COLUMN "tickets"."attendeeEmail" IS 'Attendee email or contact info'`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD "attendeeName" character varying`);
        await queryRunner.query(`COMMENT ON COLUMN "tickets"."attendeeName" IS 'Attendee name'`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD "ticketTypeId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD "eventId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD "scannedAt" TIMESTAMP`);
        await queryRunner.query(`COMMENT ON COLUMN "tickets"."scannedAt" IS 'When ticket was scanned/used'`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD "refundedAt" TIMESTAMP`);
        await queryRunner.query(`COMMENT ON COLUMN "tickets"."refundedAt" IS 'When ticket was refunded'`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD "code" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "UQ_c6e20a830c0f8b571abd331b775" UNIQUE ("code")`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD "title" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD "maxUses" integer NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD "usageCount" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD "expiresAt" TIMESTAMP NOT NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_986a0e7a5cc4bddaf417728250"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_698f411fd2aca313683603485a"`);
        await queryRunner.query(`ALTER TYPE "public"."tickets_status_enum" RENAME TO "tickets_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."tickets_status_enum" AS ENUM('active', 'used', 'expired', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "tickets" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tickets" ALTER COLUMN "status" TYPE "public"."tickets_status_enum" USING "status"::"text"::"public"."tickets_status_enum"`);
        await queryRunner.query(`ALTER TABLE "tickets" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."tickets_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD "metadata" jsonb`);
        await queryRunner.query(`CREATE INDEX "IDX_7094a7713eda319cf663dc9334" ON "tickets" ("orderReference") `);
        await queryRunner.query(`CREATE INDEX "IDX_986a0e7a5cc4bddaf417728250" ON "tickets" ("eventId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_698f411fd2aca313683603485a" ON "tickets" ("ticketTypeId", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_ticket_expires_at" ON "tickets" ("expiresAt") `);
        await queryRunner.query(`CREATE INDEX "idx_ticket_status" ON "tickets" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_ticket_code" ON "tickets" ("code") `);
        await queryRunner.query(`ALTER TABLE "ticket_types" ADD CONSTRAINT "FK_0bf6c025aea56d71d7c0a019f9e" FOREIGN KEY ("eventId") REFERENCES "event"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_9ff866ea2cad94fc6a8106e6909" FOREIGN KEY ("ticketTypeId") REFERENCES "ticket_types"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_8a101375d173c39a7c1d02c9d7d" FOREIGN KEY ("eventId") REFERENCES "event"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_8a101375d173c39a7c1d02c9d7d"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_9ff866ea2cad94fc6a8106e6909"`);
        await queryRunner.query(`ALTER TABLE "ticket_types" DROP CONSTRAINT "FK_0bf6c025aea56d71d7c0a019f9e"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ticket_code"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ticket_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ticket_expires_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_698f411fd2aca313683603485a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_986a0e7a5cc4bddaf417728250"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7094a7713eda319cf663dc9334"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD "metadata" character varying`);
        await queryRunner.query(`CREATE TYPE "public"."tickets_status_enum_old" AS ENUM('issued', 'scanned', 'refunded', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "tickets" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tickets" ALTER COLUMN "status" TYPE "public"."tickets_status_enum_old" USING "status"::"text"::"public"."tickets_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "tickets" ALTER COLUMN "status" SET DEFAULT 'issued'`);
        await queryRunner.query(`DROP TYPE "public"."tickets_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."tickets_status_enum_old" RENAME TO "tickets_status_enum"`);
        await queryRunner.query(`CREATE INDEX "IDX_698f411fd2aca313683603485a" ON "tickets" ("ticketTypeId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_986a0e7a5cc4bddaf417728250" ON "tickets" ("eventId", "status") `);
        await queryRunner.query(`ALTER TABLE "tickets" DROP COLUMN "expiresAt"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP COLUMN "usageCount"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP COLUMN "maxUses"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "UQ_c6e20a830c0f8b571abd331b775"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP COLUMN "code"`);
        await queryRunner.query(`COMMENT ON COLUMN "tickets"."refundedAt" IS 'When ticket was refunded'`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP COLUMN "refundedAt"`);
        await queryRunner.query(`COMMENT ON COLUMN "tickets"."scannedAt" IS 'When ticket was scanned/used'`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP COLUMN "scannedAt"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP COLUMN "eventId"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP COLUMN "ticketTypeId"`);
        await queryRunner.query(`COMMENT ON COLUMN "tickets"."attendeeName" IS 'Attendee name'`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP COLUMN "attendeeName"`);
        await queryRunner.query(`COMMENT ON COLUMN "tickets"."attendeeEmail" IS 'Attendee email or contact info'`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP COLUMN "attendeeEmail"`);
        await queryRunner.query(`COMMENT ON COLUMN "tickets"."orderReference" IS 'Reference to order/transaction if purchased'`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP COLUMN "orderReference"`);
        await queryRunner.query(`COMMENT ON COLUMN "tickets"."qrCode" IS 'Unique QR code identifier for scanning'`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "UQ_fededfa934cf8d7214adfa6c824"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP COLUMN "qrCode"`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD "refundedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD "scannedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD "eventId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD "ticketTypeId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD "attendeeName" character varying`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD "attendeeEmail" character varying`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD "orderReference" character varying`);
        await queryRunner.query(`CREATE INDEX "IDX_7094a7713eda319cf663dc9334" ON "tickets" ("orderReference") `);
        await queryRunner.query(`ALTER TABLE "tickets" ADD "qrCode" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "UQ_fededfa934cf8d7214adfa6c824" UNIQUE ("qrCode")`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TYPE "public"."user_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_349ebd8ed5a92c62ae7019d954"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_73c17c036d025e548b4a08edfe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_076bdf5608ee894054033d1e7f"`);
        await queryRunner.query(`DROP TABLE "blockchain_anchor"`);
        await queryRunner.query(`DROP TYPE "public"."blockchain_anchor_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."blockchain_anchor_entitytype_enum"`);
        await queryRunner.query(`DROP TABLE "contact_messages"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_698f411fd2aca313683603485a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_986a0e7a5cc4bddaf417728250"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7094a7713eda319cf663dc9334"`);
        await queryRunner.query(`DROP TABLE "tickets"`);
        await queryRunner.query(`DROP TYPE "public"."tickets_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5ce97de5dda8351bef7c2205a5"`);
        await queryRunner.query(`DROP TABLE "ticket_types"`);
        await queryRunner.query(`DROP TYPE "public"."ticket_types_pricetype_enum"`);
        await queryRunner.query(`DROP TABLE "event"`);
        await queryRunner.query(`DROP TYPE "public"."event_blockchainstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."event_status_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e89714329d20292076695c82b3"`);
        await queryRunner.query(`DROP TABLE "verification_log_entity"`);
        await queryRunner.query(`DROP TYPE "public"."verification_log_entity_status_enum"`);
    }

}
